name: General checks

on:
  push:
    branches: [main]
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]  # added `ready_for_review` since draft is skipped
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check-schema:
    uses: Lightning-AI/utilities/.github/workflows/check-schema.yml@main
    with:
      azure-dir: ''

  check-package:
    if: github.event.pull_request.draft == false
    uses: Lightning-AI/utilities/.github/workflows/check-package.yml@main
    with:
      actions-ref: main
      artifact-name: dist-packages-${{ github.sha }}
      import-name: "litlogger"
      install-flags: "--extra-index-url https://download.pytorch.org/whl/cpu"
      testing-matrix: |
        {
          "os": ["ubuntu-22.04", "ubuntu-24.04", "macos-14"],
          "python-version": ["3.10", "3.11", "3.12", "3.13"],
        }

  pre-commit:
    uses: Lightning-AI/utilities/.github/workflows/check-precommit.yml@main
